version: 2

project_name: triage

builds:
  - id: triage
    binary: triage
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/spiffcs/triage/cmd.version={{ .Version }}
      - -X github.com/spiffcs/triage/cmd.commit={{ .Commit }}
      - -X github.com/spiffcs/triage/cmd.date={{ .Date }}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next+{{ .ShortCommit }}"

signs:
  - cmd: .tool/cosign
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--bundle=${signature}"
      - "--yes"
      - "${artifact}"
    artifacts: checksum

release:
  github:
    owner: spiffcs
    name: triage
  draft: false
  prerelease: auto
  make_latest: true
  footer: |
    ---
    **Verification:**
    ```bash
    cosign verify-blob \
        --bundle checksums.txt.sigstore.json \
        --certificate-identity-regexp "^https://github.com/spiffcs/triage/.*" \
        --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
        checksums.txt
    ```
